[package]
name = "progscrape-application"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.28.0"
serde_rusqlite = "0.31.0"
tantivy = "0.19.0"
base64 = "0.21.0"
progscrape-scrapers = { path = "../scrapers" }

[dev-dependencies]
rstest = "0.16.0"
