[package]
name = "progscrape-application"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_rusqlite = "0.31.0"
serde_json = "1.0"

rusqlite = "0.28.0"
tantivy = "0.19.1"
base64 = "0.21.0"
itertools = "0.10.5"

progscrape-scrapers = { path = "../scrapers" }

[dev-dependencies]
rstest = "0.16.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
