[package]
name = "progscrape-scrapers"
version = "0.1.0"
edition = "2021"

[dependencies]
tl = "0.7.7"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_cbor = "0.11"
roxmltree = "0.17.0"
thiserror = "1.0.38"
url = "2.3.1"
itertools = "0.10.5"
regex = "1.7.0"
flate2 = "1.0"
lazy_static = "1.4"
base64 = "0.21.0"
enumset = "1.0"

[dev-dependencies]
rstest = "0.16.0"
