[package]
name = "progscrape-web"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_cbor = "0.11"
lazy_static = "1.4"
itertools = "0.10.5"

tera = "1.17.1"
axum = { version = "0.6.1", features = ["ws"] }
hyper = "0.14"
tokio = { version = "1.23.0", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
num-format = "0.4.4"
sha2 = "0.10"
infer = "0.12"
grass = "0.12"
notify = "5.0.0"
rand = "0.8.5"
reqwest = "0.11"

clap = { version = "4.1", features = ["derive"] }

# For cron
chrono = { version = "0.4", features = ["serde"] }

progscrape-scrapers = { path = "../scrapers" }
progscrape-application = { path = "../application" }

[dev-dependencies]
rstest = "0.16.0"
